import { Injectable } from "@nestjs/common";
import { ElasticsearchService } from '@nestjs/elasticsearch';

@Injectable()
export class CustomElasticsearchService {
    private readonly indexName = 'products';
    constructor(private readonly esService: ElasticsearchService) { }

    async createIndexAndSeedData() {
        try {
            // Delete index if it exists (for fresh start)
            const indexExists = await this.esService.indices.exists({
                index: this.indexName,
            });

            if (indexExists) {
                await this.esService.indices.delete({ index: this.indexName });
                console.log(`Index '${this.indexName}' deleted`);
            }

            // Create index with comprehensive mappings
            await this.esService.indices.create({
                index: this.indexName,
                mappings: {
                    properties: {
                        title: { type: 'text', analyzer: 'standard' },
                        description: { type: 'text', analyzer: 'standard' },
                        content: { type: 'text', analyzer: 'standard' },
                        tags: { type: 'keyword' },
                        category: { type: 'keyword' },
                        brand: { type: 'keyword' },
                        status: { type: 'keyword' },
                        price: { type: 'float' },
                        rating: { type: 'float' },
                        views: { type: 'integer' },
                        stock: { type: 'integer' },
                        isActive: { type: 'boolean' },
                        featured: { type: 'boolean' },
                        inStock: { type: 'boolean' },
                        createdAt: { type: 'date' },
                        updatedAt: { type: 'date' },
                        publishedAt: { type: 'date' },
                        discount: { type: 'integer' },
                        sku: { type: 'keyword' },
                    },
                },
            });
            console.log(`Index '${this.indexName}' created successfully`);

            // Seed diverse sample data
            const sampleProducts = [
                {
                    title: 'Premium Laptop Pro 15',
                    description: 'High-performance laptop for professionals with advanced graphics',
                    content: 'This laptop features a powerful processor, excellent display quality, and long battery life. Perfect for developers and designers.',
                    tags: ['electronics', 'laptop', 'computing', 'professional'],
                    category: 'Electronics',
                    brand: 'TechBrand',
                    status: 'active',
                    price: 1299.99,
                    rating: 4.8,
                    views: 15234,
                    stock: 45,
                    isActive: true,
                    featured: true,
                    inStock: true,
                    createdAt: new Date('2024-01-15'),
                    updatedAt: new Date('2024-02-20'),
                    publishedAt: new Date('2024-01-16'),
                    discount: 10,
                    sku: 'LAP-001',
                },
                {
                    title: 'Wireless Ergonomic Mouse',
                    description: 'Ergonomic wireless mouse with long battery life and precision tracking',
                    content: 'Comfortable design reduces wrist strain. Features include silent clicking and smooth scrolling.',
                    tags: ['electronics', 'mouse', 'wireless', 'accessories'],
                    category: 'Electronics',
                    brand: 'MousePro',
                    status: 'active',
                    price: 29.99,
                    rating: 4.5,
                    views: 8765,
                    stock: 120,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-02-01'),
                    updatedAt: new Date('2024-02-15'),
                    publishedAt: new Date('2024-02-02'),
                    discount: 15,
                    sku: 'MOU-002',
                },
                {
                    title: 'Automatic Coffee Maker',
                    description: 'Programmable coffee maker with timer and thermal carafe',
                    content: 'Wake up to fresh coffee every morning. Features include auto-shutoff and strength control.',
                    tags: ['kitchen', 'coffee', 'appliance', 'home'],
                    category: 'Kitchen',
                    brand: 'BrewMaster',
                    status: 'active',
                    price: 79.99,
                    rating: 4.2,
                    views: 5432,
                    stock: 30,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-01-10'),
                    updatedAt: new Date('2024-01-25'),
                    publishedAt: new Date('2024-01-11'),
                    discount: 0,
                    sku: 'CFM-003',
                },
                {
                    title: 'Professional Running Shoes',
                    description: 'Comfortable running shoes designed for daily exercise and marathon training',
                    content: 'Lightweight design with excellent cushioning. Ideal for both road and trail running.',
                    tags: ['sports', 'shoes', 'running', 'fitness'],
                    category: 'Sports',
                    brand: 'RunFast',
                    status: 'active',
                    price: 89.99,
                    rating: 4.6,
                    views: 12345,
                    stock: 67,
                    isActive: true,
                    featured: true,
                    inStock: true,
                    createdAt: new Date('2024-01-20'),
                    updatedAt: new Date('2024-02-18'),
                    publishedAt: new Date('2024-01-21'),
                    discount: 20,
                    sku: 'RUN-004',
                },
                {
                    title: 'Smartphone X Pro Max',
                    description: 'Latest smartphone with advanced camera system and 5G connectivity',
                    content: 'Features include professional-grade photography, ultra-fast processing, and all-day battery life.',
                    tags: ['electronics', 'phone', 'smartphone', 'mobile'],
                    category: 'Electronics',
                    brand: 'PhoneTech',
                    status: 'active',
                    price: 899.99,
                    rating: 4.9,
                    views: 45678,
                    stock: 25,
                    isActive: true,
                    featured: true,
                    inStock: true,
                    createdAt: new Date('2024-02-05'),
                    updatedAt: new Date('2024-02-19'),
                    publishedAt: new Date('2024-02-06'),
                    discount: 5,
                    sku: 'PHN-005',
                },
                {
                    title: 'Mechanical Keyboard RGB',
                    description: 'Mechanical keyboard with RGB backlighting and customizable keys',
                    content: 'Tactile switches provide satisfying typing experience. Perfect for gaming and coding.',
                    tags: ['electronics', 'keyboard', 'gaming', 'accessories'],
                    category: 'Electronics',
                    brand: 'KeyBoardPro',
                    status: 'active',
                    price: 149.99,
                    rating: 4.7,
                    views: 9876,
                    stock: 0,
                    isActive: true,
                    featured: false,
                    inStock: false,
                    createdAt: new Date('2024-01-25'),
                    updatedAt: new Date('2024-02-10'),
                    publishedAt: new Date('2024-01-26'),
                    discount: 0,
                    sku: 'KEY-006',
                },
                {
                    title: 'Yoga Mat Premium',
                    description: 'Eco-friendly yoga mat with superior grip and cushioning',
                    content: 'Non-slip surface ensures safety during practice. Made from sustainable materials.',
                    tags: ['sports', 'yoga', 'fitness', 'wellness'],
                    category: 'Sports',
                    brand: 'ZenFit',
                    status: 'active',
                    price: 39.99,
                    rating: 4.4,
                    views: 6543,
                    stock: 89,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-02-08'),
                    updatedAt: new Date('2024-02-12'),
                    publishedAt: new Date('2024-02-09'),
                    discount: 25,
                    sku: 'YOG-007',
                },
                {
                    title: 'Bluetooth Headphones',
                    description: 'Noise-cancelling wireless headphones with premium sound quality',
                    content: 'Active noise cancellation blocks ambient noise. Battery lasts up to 30 hours.',
                    tags: ['electronics', 'headphones', 'audio', 'wireless'],
                    category: 'Electronics',
                    brand: 'AudioPro',
                    status: 'active',
                    price: 199.99,
                    rating: 4.6,
                    views: 23456,
                    stock: 52,
                    isActive: true,
                    featured: true,
                    inStock: true,
                    createdAt: new Date('2024-01-30'),
                    updatedAt: new Date('2024-02-17'),
                    publishedAt: new Date('2024-01-31'),
                    discount: 12,
                    sku: 'AUD-008',
                },
                {
                    title: 'Stainless Steel Water Bottle',
                    description: 'Insulated water bottle keeps drinks cold for 24 hours',
                    content: 'Double-wall insulation maintains temperature. BPA-free and dishwasher safe.',
                    tags: ['kitchen', 'bottle', 'hydration', 'eco-friendly'],
                    category: 'Kitchen',
                    brand: 'HydroPro',
                    status: 'active',
                    price: 24.99,
                    rating: 4.3,
                    views: 3456,
                    stock: 150,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-02-03'),
                    updatedAt: new Date('2024-02-14'),
                    publishedAt: new Date('2024-02-04'),
                    discount: 0,
                    sku: 'BOT-009',
                },
                {
                    title: 'Gaming Monitor 4K',
                    description: '27-inch 4K gaming monitor with 144Hz refresh rate',
                    content: 'Crystal clear visuals and smooth gameplay. Supports HDR for enhanced graphics.',
                    tags: ['electronics', 'monitor', 'gaming', 'display'],
                    category: 'Electronics',
                    brand: 'MonitorTech',
                    status: 'active',
                    price: 449.99,
                    rating: 4.8,
                    views: 17890,
                    stock: 18,
                    isActive: true,
                    featured: true,
                    inStock: true,
                    createdAt: new Date('2024-01-18'),
                    updatedAt: new Date('2024-02-16'),
                    publishedAt: new Date('2024-01-19'),
                    discount: 8,
                    sku: 'MON-010',
                },
                {
                    title: 'Fitness Tracker Smart Watch',
                    description: 'Advanced fitness tracker with heart rate monitoring and GPS',
                    content: 'Track your workouts, sleep, and daily activity. Water-resistant design.',
                    tags: ['electronics', 'watch', 'fitness', 'wearable'],
                    category: 'Electronics',
                    brand: 'FitTech',
                    status: 'active',
                    price: 179.99,
                    rating: 4.5,
                    views: 11234,
                    stock: 41,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-02-07'),
                    updatedAt: new Date('2024-02-13'),
                    publishedAt: new Date('2024-02-08'),
                    discount: 30,
                    sku: 'WAT-011',
                },
                {
                    title: 'Wireless Charging Pad',
                    description: 'Fast wireless charging pad compatible with all Qi-enabled devices',
                    content: 'Charge your phone, earbuds, and smartwatch simultaneously. LED indicator shows charging status.',
                    tags: ['electronics', 'charger', 'wireless', 'accessories'],
                    category: 'Electronics',
                    brand: 'ChargePro',
                    status: 'active',
                    price: 34.99,
                    rating: 4.1,
                    views: 5678,
                    stock: 95,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-01-28'),
                    updatedAt: new Date('2024-02-11'),
                    publishedAt: new Date('2024-01-29'),
                    discount: 0,
                    sku: 'CHG-012',
                },
                {
                    title: 'Dumbbell Set Adjustable',
                    description: 'Adjustable dumbbell set with multiple weight options',
                    content: 'Space-saving design allows quick weight changes. Perfect for home gyms.',
                    tags: ['sports', 'weights', 'fitness', 'equipment'],
                    category: 'Sports',
                    brand: 'FitGear',
                    status: 'active',
                    price: 249.99,
                    rating: 4.7,
                    views: 8901,
                    stock: 22,
                    isActive: true,
                    featured: true,
                    inStock: true,
                    createdAt: new Date('2024-01-12'),
                    updatedAt: new Date('2024-02-05'),
                    publishedAt: new Date('2024-01-13'),
                    discount: 15,
                    sku: 'DUM-013',
                },
                {
                    title: 'Stand Mixer Kitchen',
                    description: 'Professional stand mixer with multiple attachments',
                    content: 'Powerful motor handles heavy dough. Includes whisk, paddle, and dough hook.',
                    tags: ['kitchen', 'mixer', 'appliance', 'baking'],
                    category: 'Kitchen',
                    brand: 'ChefPro',
                    status: 'active',
                    price: 329.99,
                    rating: 4.9,
                    views: 7654,
                    stock: 14,
                    isActive: true,
                    featured: true,
                    inStock: true,
                    createdAt: new Date('2024-01-22'),
                    updatedAt: new Date('2024-02-08'),
                    publishedAt: new Date('2024-01-23'),
                    discount: 0,
                    sku: 'MIX-014',
                },
                {
                    title: 'External SSD Drive',
                    description: 'Fast portable SSD with USB-C connectivity',
                    content: 'Transfer files at lightning speed. Rugged design withstands drops and water.',
                    tags: ['electronics', 'storage', 'ssd', 'computer'],
                    category: 'Electronics',
                    brand: 'StoragePro',
                    status: 'active',
                    price: 129.99,
                    rating: 4.6,
                    views: 6789,
                    stock: 58,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-02-01'),
                    updatedAt: new Date('2024-02-15'),
                    publishedAt: new Date('2024-02-02'),
                    discount: 10,
                    sku: 'SSD-015',
                },
                {
                    title: 'Camping Tent 4 Person',
                    description: 'Weatherproof camping tent with easy setup',
                    content: 'Spacious interior accommodates four people comfortably. Includes rainfly and carrying bag.',
                    tags: ['sports', 'camping', 'outdoor', 'tent'],
                    category: 'Sports',
                    brand: 'OutdoorPro',
                    status: 'active',
                    price: 159.99,
                    rating: 4.4,
                    views: 4321,
                    stock: 33,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-01-27'),
                    updatedAt: new Date('2024-02-09'),
                    publishedAt: new Date('2024-01-28'),
                    discount: 20,
                    sku: 'TEN-016',
                },
                {
                    title: 'Electric Toothbrush',
                    description: 'Sonic electric toothbrush with multiple cleaning modes',
                    content: 'Removes plaque effectively. Features include timer and pressure sensor.',
                    tags: ['health', 'toothbrush', 'personal care', 'hygiene'],
                    category: 'Health',
                    brand: 'DentalPro',
                    status: 'active',
                    price: 69.99,
                    rating: 4.5,
                    views: 12345,
                    stock: 76,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-02-04'),
                    updatedAt: new Date('2024-02-18'),
                    publishedAt: new Date('2024-02-05'),
                    discount: 0,
                    sku: 'TOO-017',
                },
                {
                    title: 'Smart Light Bulbs Pack',
                    description: 'WiFi-enabled smart LED bulbs with color changing',
                    content: 'Control brightness and color from your phone. Works with voice assistants.',
                    tags: ['electronics', 'smart home', 'lighting', 'automation'],
                    category: 'Electronics',
                    brand: 'SmartHome',
                    status: 'active',
                    price: 49.99,
                    rating: 4.3,
                    views: 9876,
                    stock: 112,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-01-26'),
                    updatedAt: new Date('2024-02-07'),
                    publishedAt: new Date('2024-01-27'),
                    discount: 18,
                    sku: 'BUL-018',
                },
                {
                    title: 'Protein Powder Supplement',
                    description: 'Whey protein powder for muscle recovery',
                    content: 'High-quality protein with essential amino acids. Mixes easily with water or milk.',
                    tags: ['health', 'supplement', 'fitness', 'nutrition'],
                    category: 'Health',
                    brand: 'FitNutrition',
                    status: 'active',
                    price: 54.99,
                    rating: 4.6,
                    views: 15678,
                    stock: 0,
                    isActive: true,
                    featured: false,
                    inStock: false,
                    createdAt: new Date('2024-02-06'),
                    updatedAt: new Date('2024-02-19'),
                    publishedAt: new Date('2024-02-07'),
                    discount: 0,
                    sku: 'PRO-019',
                },
                {
                    title: 'Action Camera 4K',
                    description: 'Waterproof action camera for sports and adventures',
                    content: 'Record in stunning 4K quality. Compact design mounts anywhere.',
                    tags: ['electronics', 'camera', 'action', 'recording'],
                    category: 'Electronics',
                    brand: 'ActionCam',
                    status: 'active',
                    price: 279.99,
                    rating: 4.7,
                    views: 13456,
                    stock: 29,
                    isActive: true,
                    featured: true,
                    inStock: true,
                    createdAt: new Date('2024-01-14'),
                    updatedAt: new Date('2024-02-06'),
                    publishedAt: new Date('2024-01-15'),
                    discount: 12,
                    sku: 'CAM-020',
                },
                {
                    title: 'Basketball Official Size',
                    description: 'Official size basketball with superior grip',
                    content: 'Durable composite leather construction. Perfect for indoor and outdoor play.',
                    tags: ['sports', 'basketball', 'ball', 'team sports'],
                    category: 'Sports',
                    brand: 'BallPro',
                    status: 'active',
                    price: 44.99,
                    rating: 4.5,
                    views: 7890,
                    stock: 87,
                    isActive: true,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-02-02'),
                    updatedAt: new Date('2024-02-20'),
                    publishedAt: new Date('2024-02-03'),
                    discount: 0,
                    sku: 'BAS-021',
                },
                {
                    title: 'Smart Thermostat',
                    description: 'WiFi programmable thermostat for energy savings',
                    content: 'Learn your schedule and adjust automatically. Reduces energy costs significantly.',
                    tags: ['electronics', 'smart home', 'thermostat', 'automation'],
                    category: 'Electronics',
                    brand: 'SmartHome',
                    status: 'active',
                    price: 199.99,
                    rating: 4.8,
                    views: 10234,
                    stock: 36,
                    isActive: true,
                    featured: true,
                    inStock: true,
                    createdAt: new Date('2024-01-16'),
                    updatedAt: new Date('2024-02-14'),
                    publishedAt: new Date('2024-01-17'),
                    discount: 0,
                    sku: 'THM-022',
                },
                {
                    title: 'Item Without Description',
                    description: null,
                    content: 'This item has no description field for testing exists queries',
                    tags: ['test', 'electronics'],
                    category: 'Electronics',
                    brand: 'TestBrand',
                    status: 'draft',
                    price: 19.99,
                    rating: 3.5,
                    views: 123,
                    stock: 5,
                    isActive: false,
                    featured: false,
                    inStock: true,
                    createdAt: new Date('2024-02-10'),
                    updatedAt: new Date('2024-02-10'),
                    publishedAt: null,
                    discount: null,
                    sku: 'TST-023',
                },
                {
                    title: 'Product Missing Fields',
                    content: 'This product has missing optional fields',
                    tags: ['test'],
                    category: 'Sports',
                    brand: 'TestBrand',
                    status: 'draft',
                    price: 9.99,
                    rating: 2.0,
                    views: 45,
                    stock: 0,
                    isActive: false,
                    featured: false,
                    inStock: false,
                    createdAt: new Date('2024-02-11'),
                    updatedAt: new Date('2024-02-11'),
                    discount: null,
                    sku: 'TST-024',
                },
            ];

            // Bulk index documents
            const body = sampleProducts.flatMap((product) => [
                { index: { _index: this.indexName } },
                product,
            ]);

            await this.esService.bulk({ body });
            await this.esService.indices.refresh({ index: this.indexName });

            return {
                success: true,
                message: `Index '${this.indexName}' created and seeded with ${sampleProducts.length} documents`,
                count: sampleProducts.length,
            };
        } catch (err) {
            console.error('Error creating index and seeding data: ', err);
            throw err;
        }
    }

    async search(text: string) {
        return this.esService.search({
            index: this.indexName,
            query: {
                match: {
                    name: text
                }
            }
        })
    }
}